### ISSUE TITLE
Error: Cannot find module 'app'

### ISSUE THREAD

**Issue by clehner** [dominictarr/patchbay#1]
This error appears both when I use try to run patchbay using node v4 or v6:
```
patchbay (master)@cel (node v6.2.1)$ electro .
App threw an error during load
Error: Cannot find module 'app'
    at Module._resolveFilename (module.js:438:15)
    at Function.Module._resolveFilename (/usr/local/lib/node_modules/electron-prebuilt/dist/resources/electron.asar/common/reset-search-paths.js:47:12)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/electro/index.js:24:11)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
```
Is there supposed to be an `app` somewhere?

Here is the output of `npm ls`:
```
patchbay@1.0.0 /usr/local/src/patchbay
├─┬ cont@1.0.3
│ ├── continuable@1.2.0
│ ├─┬ continuable-para@1.2.0
│ │ ├─┬ continuable-hash@0.1.4
│ │ │ └── continuable@1.1.8
│ │ └─┬ continuable-list@0.1.6
│ │   └── continuable@1.1.8
│ └── continuable-series@1.2.0
├── depject@0.1.0
├─┬ electro@0.0.6
│ └── minimist@1.2.0
├─┬ electron-prebuilt@1.2.1
│ ├─┬ electron-download@2.1.2
│ │ ├─┬ debug@2.2.0
│ │ │ └── ms@0.7.1
│ │ ├── home-path@1.0.3
│ │ ├─┬ mv@2.1.1
│ │ │ ├── ncp@2.0.0
│ │ │ └─┬ rimraf@2.4.5
│ │ │   └─┬ glob@6.0.4
│ │ │     ├─┬ inflight@1.0.5
│ │ │     │ └── wrappy@1.0.2
│ │ │     ├─┬ minimatch@3.0.0
│ │ │     │ └─┬ brace-expansion@1.1.4
│ │ │     │   ├── balanced-match@0.4.1
│ │ │     │   └── concat-map@0.0.1
│ │ │     ├── once@1.3.3
│ │ │     └── path-is-absolute@1.0.0
│ │ ├─┬ nugget@1.6.2
│ │ │ ├─┬ pretty-bytes@1.0.4
│ │ │ │ ├── get-stdin@4.0.1
│ │ │ │ └─┬ meow@3.7.0
│ │ │ │   ├─┬ camelcase-keys@2.1.0
│ │ │ │   │ └── camelcase@2.1.1
│ │ │ │   ├── decamelize@1.2.0
│ │ │ │   ├─┬ loud-rejection@1.4.1
│ │ │ │   │ ├─┬ currently-unhandled@0.4.1
│ │ │ │   │ │ └── array-find-index@1.0.1
│ │ │ │   │ └── signal-exit@2.1.2
│ │ │ │   ├── map-obj@1.0.1
│ │ │ │   ├─┬ normalize-package-data@2.3.5
│ │ │ │   │ ├── hosted-git-info@2.1.5
│ │ │ │   │ ├─┬ is-builtin-module@1.0.0
│ │ │ │   │ │ └── builtin-modules@1.1.1
│ │ │ │   │ ├── semver@5.1.0
│ │ │ │   │ └─┬ validate-npm-package-license@3.0.1
│ │ │ │   │   ├─┬ spdx-correct@1.0.2
│ │ │ │   │   │ └── spdx-license-ids@1.2.1
│ │ │ │   │   └─┬ spdx-expression-parse@1.0.2
│ │ │ │   │     └── spdx-exceptions@1.0.4
│ │ │ │   ├── object-assign@4.1.0
│ │ │ │   ├─┬ read-pkg-up@1.0.1
│ │ │ │   │ ├─┬ find-up@1.1.2
│ │ │ │   │ │ └── path-exists@2.1.0
│ │ │ │   │ └─┬ read-pkg@1.1.0
│ │ │ │   │   ├─┬ load-json-file@1.1.0
│ │ │ │   │   │ ├── graceful-fs@4.1.4
│ │ │ │   │   │ ├─┬ parse-json@2.2.0
│ │ │ │   │   │ │ └─┬ error-ex@1.3.0
│ │ │ │   │   │ │   └── is-arrayish@0.2.1
│ │ │ │   │   │ ├── pify@2.3.0
│ │ │ │   │   │ └─┬ strip-bom@2.0.0
│ │ │ │   │   │   └── is-utf8@0.2.1
│ │ │ │   │   └── path-type@1.1.0
│ │ │ │   ├─┬ redent@1.0.0
│ │ │ │   │ ├─┬ indent-string@2.1.0
│ │ │ │   │ │ └─┬ repeating@2.0.1
│ │ │ │   │ │   └─┬ is-finite@1.0.1
│ │ │ │   │ │     └── number-is-nan@1.0.0
│ │ │ │   │ └── strip-indent@1.0.1
│ │ │ │   └── trim-newlines@1.0.0
│ │ │ ├─┬ progress-stream@1.2.0
│ │ │ │ ├── speedometer@0.1.4
│ │ │ │ └─┬ through2@0.2.3
│ │ │ │   ├─┬ readable-stream@1.1.14
│ │ │ │   │ └── isarray@0.0.1
│ │ │ │   └─┬ xtend@2.1.2
│ │ │ │     └── object-keys@0.4.0
│ │ │ ├─┬ request@2.72.0
│ │ │ │ ├── aws-sign2@0.6.0
│ │ │ │ ├── aws4@1.4.1
│ │ │ │ ├─┬ bl@1.1.2
│ │ │ │ │ └─┬ readable-stream@2.0.6
│ │ │ │ │   └── isarray@1.0.0
│ │ │ │ ├── caseless@0.11.0
│ │ │ │ ├─┬ combined-stream@1.0.5
│ │ │ │ │ └── delayed-stream@1.0.0
│ │ │ │ ├── extend@3.0.0
│ │ │ │ ├── forever-agent@0.6.1
│ │ │ │ ├─┬ form-data@1.0.0-rc4
│ │ │ │ │ └── async@1.5.2
│ │ │ │ ├─┬ har-validator@2.0.6
│ │ │ │ │ ├─┬ chalk@1.1.3
│ │ │ │ │ │ ├── ansi-styles@2.2.1
│ │ │ │ │ │ ├── escape-string-regexp@1.0.5
│ │ │ │ │ │ ├─┬ has-ansi@2.0.0
│ │ │ │ │ │ │ └── ansi-regex@2.0.0
│ │ │ │ │ │ ├── strip-ansi@3.0.1
│ │ │ │ │ │ └── supports-color@2.0.0
│ │ │ │ │ ├─┬ commander@2.9.0
│ │ │ │ │ │ └── graceful-readlink@1.0.1
│ │ │ │ │ ├─┬ is-my-json-valid@2.13.1
│ │ │ │ │ │ ├── generate-function@2.0.0
│ │ │ │ │ │ ├─┬ generate-object-property@1.2.0
│ │ │ │ │ │ │ └── is-property@1.0.2
│ │ │ │ │ │ ├── jsonpointer@2.0.0
│ │ │ │ │ │ └── xtend@4.0.1
│ │ │ │ │ └─┬ pinkie-promise@2.0.1
│ │ │ │ │   └── pinkie@2.0.4
│ │ │ │ ├─┬ hawk@3.1.3
│ │ │ │ │ ├── boom@2.10.1
│ │ │ │ │ ├── cryptiles@2.0.5
│ │ │ │ │ ├── hoek@2.16.3
│ │ │ │ │ └── sntp@1.0.9
│ │ │ │ ├─┬ http-signature@1.1.1
│ │ │ │ │ ├── assert-plus@0.2.0
│ │ │ │ │ ├─┬ jsprim@1.2.2
│ │ │ │ │ │ ├── extsprintf@1.0.2
│ │ │ │ │ │ ├── json-schema@0.2.2
│ │ │ │ │ │ └── verror@1.3.6
│ │ │ │ │ └─┬ sshpk@1.8.3
│ │ │ │ │   ├── asn1@0.2.3
│ │ │ │ │   ├── assert-plus@1.0.0
│ │ │ │ │   ├─┬ dashdash@1.14.0
│ │ │ │ │   │ └── assert-plus@1.0.0
│ │ │ │ │   ├── ecc-jsbn@0.1.1
│ │ │ │ │   ├─┬ getpass@0.1.6
│ │ │ │ │   │ └── assert-plus@1.0.0
│ │ │ │ │   ├── jodid25519@1.0.2
│ │ │ │ │   └── jsbn@0.1.0
│ │ │ │ ├── is-typedarray@1.0.0
│ │ │ │ ├── isstream@0.1.2
│ │ │ │ ├── json-stringify-safe@5.0.1
│ │ │ │ ├── node-uuid@1.4.7
│ │ │ │ ├── oauth-sign@0.8.2
│ │ │ │ ├── qs@6.1.0
│ │ │ │ ├── stringstream@0.0.5
│ │ │ │ ├── tough-cookie@2.2.2
│ │ │ │ └── tunnel-agent@0.4.3
│ │ │ ├── single-line-log@0.4.1
│ │ │ └── throttleit@0.0.2
│ │ ├── path-exists@1.0.0
│ │ └─┬ rc@1.1.6
│ │   ├── ini@1.3.4
│ │   └── strip-json-comments@1.0.4
│ └─┬ extract-zip@1.5.0
│   ├─┬ concat-stream@1.5.0
│   │ ├── inherits@2.0.1
│   │ ├─┬ readable-stream@2.0.6
│   │ │ ├── core-util-is@1.0.2
│   │ │ ├── isarray@1.0.0
│   │ │ ├── process-nextick-args@1.0.7
│   │ │ ├── string_decoder@0.10.31
│   │ │ └── util-deprecate@1.0.2
│   │ └── typedarray@0.0.6
│   ├── debug@0.7.4
│   ├─┬ mkdirp@0.5.0
│   │ └── minimist@0.0.8
│   └─┬ yauzl@2.4.1
│     └─┬ fd-slicer@1.0.1
│       └── pend@1.2.0
├─┬ hyperscript@1.4.7
│ ├── browser-split@0.0.0
│ ├─┬ class-list@0.1.1
│ │ └── indexof@0.0.1
│ └── html-element@1.3.0
├─┬ mime-types@2.1.11
│ └── mime-db@1.23.0
├── moment@2.13.0
├── pull-cat@1.1.9
├── pull-next@0.0.0
├── pull-paramap@1.1.6
├─┬ pull-scroll@0.1.0
│ ├── observable@2.1.4
│ ├── pull-pause@0.0.0
│ └── request-animation-loop@0.1.0
├── pull-stream@3.4.0
├── split-buffer@1.0.0
├── ssb-avatar@0.0.0
├─┬ ssb-client@3.1.0
│ ├── explain-error@1.0.1
│ ├─┬ secret-stack@2.5.1
│ │ ├── hoox@0.0.1
│ │ ├── map-merge@1.1.0
│ │ ├─┬ muxrpc@6.3.3
│ │ │ ├── packet-stream@2.0.0
│ │ │ ├─┬ packet-stream-codec@1.1.1
│ │ │ │ └─┬ pull-through@1.0.18
│ │ │ │   └── looper@3.0.0
│ │ │ └── pull-goodbye@0.0.1
│ │ ├─┬ non-private-ip@1.3.0
│ │ │ └── ip@0.3.3
│ │ ├─┬ pull-inactivity@2.1.1
│ │ │ ├── pull-abortable@4.0.0
│ │ │ └── pull-stream@2.26.1
│ │ ├─┬ pull-stream@2.27.0
│ │ │ └── pull-core@1.1.0
│ │ ├─┬ secret-handshake@0.4.1
│ │ │ ├── deep-equal@1.0.1
│ │ │ ├─┬ pull-box-stream@1.0.11
│ │ │ │ └── increment-buffer@1.0.0
│ │ │ ├── pull-defer@0.2.2
│ │ │ ├─┬ pull-handshake@1.1.2
│ │ │ │ └── pull-delayed-sink@1.0.0
│ │ │ ├── pull-pair@1.1.0
│ │ │ ├── pull-pushable@2.0.0
│ │ │ └── pull-reader@1.2.5
│ │ └── stream-to-pull-stream@1.6.8
│ └─┬ ssb-config@1.2.1
│   ├── deep-extend@0.4.1
│   ├─┬ osenv@0.1.3
│   │ ├── os-homedir@1.0.1
│   │ └── os-tmpdir@1.0.1
│   └─┬ rc@0.6.0
│     ├── deep-extend@0.2.11
│     ├── minimist@0.0.10
│     └── strip-json-comments@0.1.3
├─┬ ssb-keys@5.0.2
│ ├── blake2s@1.0.1
│ ├─┬ chloride@2.1.1
│ │ ├─┬ chloridedown@1.0.22
│ │ │ └── nan@2.3.5
│ │ ├─┬ sodium-browserify@1.1.2
│ │ │ ├─┬ libsodium-wrappers@0.2.12
│ │ │ │ └── libsodium@0.2.12
│ │ │ ├── sha.js@2.4.5
│ │ │ └── tweetnacl@0.14.3
│ │ └─┬ sodium-browserify-tweetnacl@0.1.0
│ │   ├─┬ ed2curve@0.1.4
│ │   │ └── tweetnacl@0.13.3
│ │   ├── tweetnacl@0.14.3
│ │   └── tweetnacl-auth@0.3.0
│ ├── deep-equal@0.2.2
│ ├── hmac@1.0.1
│ ├─┬ mkdirp@0.5.1
│ │ └── minimist@0.0.8
│ ├── private-box@0.0.3
│ └─┬ ssb-ref@2.3.0
│   ├── ip-regex@1.0.3
│   └── is-valid-domain@0.0.2
├─┬ ssb-markdown@3.0.0
│ ├── emoji-named-characters@1.0.2
│ ├── ssb-marked@0.5.4
│ └── ssb-msgs@5.2.0
├── ssb-mentions@0.1.0
├── ssb-sort@0.0.0
└─┬ suggest-box@2.0.0
  └── textarea-caret-position@0.1.1
```

**Comment by dominictarr** [comment]
oh, sorry this uses my electron wrapper [electro](https://github.com/dominictarr/electro) which currently works only with electron 0.37.

**Comment by dominictarr** [comment]
it probably wouldn't be difficult to fix... just figuring out what they changed the apis to.
