### ISSUE TITLE
Param 0 must have a .content of type "object"

### ISSUE THREAD

**Issue by evbogue** [dominictarr/patchbay#23]
This error appears when I try to send private messages in Patchbay.

I've gotten this error a few times since pulling the latest master.

When I hit the Publish button and confirm, this appears in the errors tab:

```
Param 0 must have a .content of type "object"
UsageError: Param 0 must have a .content of type "object"
    at Error.ZE (/home/ev/builds/patchwork/node_modules/zerr/index.js:11:42)
    at ZError (/home/ev/builds/patchwork/node_modules/zerr/index.js:13:14)
    at Object.module.exports.valid.msg (/home/ev/builds/patchwork/node_modules/scuttlebot/lib/validators.js:42:14)
    at validate (/home/ev/builds/patchwork/node_modules/muxrpc-validation/index.js:130:15)
    at Object.<anonymous> (/home/ev/builds/patchwork/node_modules/muxrpc-validation/index.js:78:17)
    at Object.hooked (/home/ev/builds/patchwork/node_modules/hoox/index.js:10:15)
    at Object.localCall (/home/ev/builds/patchwork/node_modules/muxrpc/local-api.js:31:31)
    at Object.<anonymous> (/home/ev/builds/patchwork/node_modules/muxrpc/local-api.js:37:22)
    at Object.PacketStream.request (/home/ev/builds/patchwork/node_modules/muxrpc/stream.js:46:17)
    at PacketStream._onrequest (/home/ev/builds/patchwork/node_modules/packet-stream/index.js:149:17)
```

**Comment by dominictarr** [comment]
ah, you just need to have the latest version of scuttlebot.
if you are using patchwork as the server,
you should get this:
```
$ npm ls scuttlebot
ssb-patchwork@2.8.4 /home/dominic/c/patchwork
`-- scuttlebot@8.3.5 
```

`npm install scuttlebot` should fix it.

**Comment by evbogue** [comment]
Yes, fixed.
