### ISSUE TITLE
no blob crash

### ISSUE THREAD

**Issue by evbogue** [dominictarr/patchbay#50]
On pulling 1.8.2 sbot server is crashing on my local when I run `CHLORIDE_JS=1 electro index.js` on my local. I (re)installed ssb-ws, ssb-links, and ssb-query just to be sure that wasn't it.

```
Error: no blob:&qjeAs8+uMXLlyovT4JnEpMwTNDx/QXHfOl2nv2u0VCM=.sha256
    at /home/ev/.ssb/node_modules/ssb-ws/node_modules/multiblob-http/index.j
s:39:23
    at /usr/lib/node_modules/scuttlebot/node_modules/multiblob/index.js:141:
15
    at continuation (/usr/lib/node_modules/scuttlebot/node_modules/continuab
le-list/index.js:24:25)
    at /usr/lib/node_modules/scuttlebot/node_modules/multiblob/index.js:114:
9
    at done (/usr/lib/node_modules/scuttlebot/node_modules/multiblob/index.j
s:41:38)
    at FSReqWrap.oncomplete (fs.js:123:15)
/usr/lib/node_modules/scuttlebot/node_modules/libsodium/dist/modules/libsodi
um.js:14
var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};v
ar moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){
moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="ob
ject";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRO
NMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIR
ONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_
IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=nodeFS["readFileSync"](filename);if(!ret&&filename!=nodePath["resolve"](

Error: Can't render headers after they are sent to the client
    at ServerResponse.OutgoingMessage._renderHeaders (_http_outgoing.js:399:11)
    at ServerResponse.writeHead (_http_server.js:184:20)
    at /home/ev/.ssb/node_modules/ssb-ws/node_modules/multiblob-http/index.js:41:13
    at /usr/lib/node_modules/scuttlebot/node_modules/multiblob/index.js:141:15
    at continuation (/usr/lib/node_modules/scuttlebot/node_modules/continuable-list/index.js:24:25)
    at /usr/lib/node_modules/scuttlebot/node_modules/multiblob/index.js:114:9
    at done (/usr/lib/node_modules/scuttlebot/node_modules/multiblob/index.js:41:38)
    at FSReqWrap.oncomplete (fs.js:123:15)
```

**Comment by dominictarr** [comment]
that blob is the fallback image. 
the error is in     [multiblob-http/index.js:41:13](https://github.com/dominictarr/multiblob-http/blob/master/index.js#L41)

**Comment by dominictarr** [comment]
hmm, it doesn't crash for me. try updating multiblob-http. make sure it's version 0.0.1

**Comment by evbogue** [comment]
@dominictarr I tried installing multiblob-http in .ssb/node_modules as well as in the patchbay repo, and I'm still getting the error.

Do I need to change a configuration option in config.js for Patchbay to work now?

**Comment by evbogue** [comment]
The real issue was that ssb-ws is installing multiblob-http@0.0.0, updating to multiblob-http@0.0.1 solved the issue.

However, I can't find the fallback blob on the network.

**Comment by clehner** [comment]
> However, I can't find the fallback blob on the network.

```
sbot blobs.add < patchwork/ui/img/fallback.png
```

this doesn't fix the issue for everyone of course

**Comment by evbogue** [comment]
@clehner `sbot blobs.add < patchwork/ui/img/fallback.png` fixed it for me. 

The package.json for ssb-ws has been updated, so this issue can be closed.

**Comment by dominictarr** [comment]
Oh, I see that it writes ok 200 but it can still error later... https://github.com/dominictarr/multiblob-http/blob/master/index.js#L47

So I think actually we should remove that line...

We just need to make `get` trigger `want` of the blob. Then it will pull it up from my machine.
